[tool.ruff]
# Same as Black.
line-length = 127
# Assume Python 3.8
target-version = "py38"
# See https://beta.ruff.rs/docs/rules/
select = ["E", "F", "B", "UP", "C90", "RUF"]
# B028: Ignore explicit stacklevel`
ignore = ["B028"]

[tool.ruff.per-file-ignores]
# E402: module level not at top (because silencing tensorflow)
"visualize_dataset.py" = ["E402"]
"test_dataset_transform.py" = ["E402"]

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 15

[tool.black]
line-length = 127

[tool.isort]
profile = "black"
line_length = 127
src_paths = []

[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"
show_error_codes = true
# exclude = """(?x)(
#     stable_baselines3/common/buffers.py$
#   )"""
# plugins = ["numpy.typing.mypy_plugin"]
# disable_error_code = "assignment"
